name: flutter_application_6
description: "A new Flutter project."

publish_to: 'none' # Prevent publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "images/icon2.jpg" # Path to your new app icon
  android_icon_size: 120  # You can specify custom sizes
  ios_icon_size: 180

flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/ # Include images from the assets directory
  # You can add any other asset folders you might need 
